{{ .base | strings.TrimSpace }}

RUN apk add --no-cache \
	ca-certificates \
	libcap \
	mailcap

RUN set -eux; \
	mkdir -p \
		/config/kengine \
		/data/kengine \
		/etc/kengine \
		/usr/share/kengine \
	; \
	wget -O /etc/kengine/Kenginefile "https://github.com/khulnasoft/dist/raw/{{ .config.dist_commit }}/config/Kenginefile"; \
	wget -O /usr/share/kengine/index.html "https://github.com/khulnasoft/dist/raw/{{ .config.dist_commit }}/welcome/index.html"

# https://github.com/khulnasoft/kengine/releases
ENV KENGINE_VERSION v{{ .config.kengine_version }}

RUN set -eux; \
	apkArch="$(apk --print-arch)"; \
	case "$apkArch" in \
		x86_64)  binArch='amd64'; checksum='{{ .checksums.amd64 }}' ;; \
		armhf)   binArch='armv6'; checksum='{{ .checksums.arm32v6 }}' ;; \
		armv7)   binArch='armv7'; checksum='{{ .checksums.arm32v7 }}' ;; \
		aarch64) binArch='arm64'; checksum='{{ .checksums.arm64v8 }}' ;; \
		ppc64el|ppc64le) binArch='ppc64le'; checksum='{{ .checksums.ppc64le }}' ;; \
		riscv64) binArch='riscv64'; checksum='{{ .checksums.riscv64 }}' ;; \
		s390x)   binArch='s390x'; checksum='{{ .checksums.s390x }}' ;; \
		*) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
	esac; \
	wget -O /tmp/kengine.tar.gz "https://github.com/khulnasoft/kengine/releases/download/v{{ .config.kengine_version }}/kengine_{{ .config.kengine_version }}_linux_${binArch}.tar.gz"; \
	echo "$checksum  /tmp/kengine.tar.gz" | sha512sum -c; \
	tar x -z -f /tmp/kengine.tar.gz -C /usr/bin kengine; \
	rm -f /tmp/kengine.tar.gz; \
	setcap cap_net_bind_service=+ep /usr/bin/kengine; \
	chmod +x /usr/bin/kengine; \
	kengine version

# See https://khulnasoft.com/docs/conventions#file-locations for details
ENV XDG_CONFIG_HOME /config
ENV XDG_DATA_HOME /data

LABEL org.opencontainers.image.version=v{{ .config.kengine_version }}
LABEL org.opencontainers.image.title=Kengine
LABEL org.opencontainers.image.description="a powerful, enterprise-ready, open source web server with automatic HTTPS written in Go"
LABEL org.opencontainers.image.url=https://khulnasoft.com
LABEL org.opencontainers.image.documentation=https://khulnasoft.com/docs
LABEL org.opencontainers.image.vendor="Light Code Labs"
LABEL org.opencontainers.image.licenses=Apache-2.0
LABEL org.opencontainers.image.source="https://github.com/khulnasoft/kengine-docker"

EXPOSE 80
EXPOSE 443
EXPOSE 443/udp
EXPOSE 2019

WORKDIR /srv

CMD ["kengine", "run", "--config", "/etc/kengine/Kenginefile", "--adapter", "kenginefile"]
